import {API} from '../lib/api';
import {bytes} from '../lib/format';
import type {ApiEvent, Security, Stats} from '../types';
import {BackupPanel} from './BackupPanel';
import {IntegrityPanel} from './IntegrityPanel';

export function InsightsView({stats, events, security, onLogout}: {stats: Stats; events: ApiEvent[]; security: Security | null; onLogout: () => void}) {
  return <><section className="metrics"><article><small>ORIGINAL LIBRARY</small><strong>{bytes(stats.original_bytes)}</strong><span>{stats.photos} source photos</span></article><article><small>GALLERY PAYLOAD</small><strong>{bytes(stats.thumbnail_bytes)}</strong><span>WebP derivatives</span></article><article className="highlight"><small>BANDWIDTH SAVED</small><strong>{stats.bandwidth_saved_percent}%</strong><span>Compared with originals</span></article><article><small>AVERAGE API</small><strong>{stats.average_ms || 0} ms</strong><span>{stats.request_count} measured requests</span></article><article><small>ERROR RESPONSES</small><strong>{stats.error_count || 0}</strong><span>Includes rejected anonymous calls</span></article><article><small>ORGANIZATION</small><strong>{stats.albums}</strong><span>Albums created</span></article></section>
    <section className="activity"><div><p>RECENT ACTIVITY</p><h2>Audit trail</h2></div>{events.map((event, index) => <article key={`${event.created_at}-${index}`}><i className={event.status < 400 ? 'ok' : 'bad'}/><b>{event.method}</b><span>{event.path.replace('/api/', '').replaceAll('/', ' · ')}</span><small>{event.status} · {event.duration_ms} ms</small><time>{new Date(event.created_at).toLocaleTimeString()}</time></article>)}{!events.length && <div className="empty">No write activity recorded yet.</div>}</section>
    {security && <section className="security-panel"><div><p>VAULT SECURITY</p><h2>Session protection</h2><span>{security.network_scope} · HttpOnly {security.same_site} cookie</span></div><div className="security-facts"><article><b>{security.active_sessions}</b><small>Active sessions</small></article><article><b>{security.recent_failed_logins}</b><small>Failed logins / 24h</small></article><article><b>{security.failure_limit}</b><small>Attempts per {security.failure_window_minutes} min</small></article><article><b>{security.session_ttl_hours}h</b><small>Session lifetime</small></article></div><button onClick={async () => {if (!confirm('Sign out every active PixelVault session?')) return; await fetch(`${API}/security/revoke-all`, {method: 'POST'}); onLogout();}}>Revoke all sessions</button></section>}
    <IntegrityPanel/><BackupPanel/></>;
}
